const goodnightMessages = [
    "Que la nuit t'enveloppe de douceur et que tes rêves soient les plus beaux.",
    "Bonne nuit, dors bien, et pense un peu à moi avant de fermer les yeux.",
    "Les étoiles brillent ce soir, mais pas autant que mon envie de te souhaiter une belle nuit.",
    "Ferme les yeux, laisse-toi porter, demain sera un jour meilleur.",
    "Que cette nuit t'apporte le repos et que ton réveil soit plein de sourires.",
    "La lune veille sur toi ce soir, dors tranquille.",
    "Chaque nuit est une pause avant un nouveau jour plein de possibilités, bonne nuit.",
    "Rêve grand, dors bien, et réveille-toi encore plus fort.",
    "Que le sommeil efface les fatigues du jour et t'apporte une belle énergie demain.",
    "Bonne nuit, que tes rêves soient à la hauteur de la personne merveilleuse que tu es.",
    "Le silence de la nuit porte toujours de belles pensées, bonne nuit à toi.",
    "Repose-toi bien, demain t'attend avec de nouvelles opportunités.",
    "Que ton sommeil soit paisible et tes rêves pleins de douceur.",
    "La journée s'achève, laisse la nuit prendre soin de toi. Bonne nuit.",
    "Dors bien, et n'oublie pas que demain est une nouvelle page blanche.",
    "Que les anges veillent sur ton sommeil cette nuit.",
    "Ferme les yeux et laisse partir tous les soucis de la journée. Bonne nuit.",
    "Chaque étoile ce soir te souhaite une nuit douce et reposante.",
    "Bonne nuit, que le calme de la nuit apaise ton esprit.",
    "Dors sur tes deux oreilles, demain sera encore meilleur.",
    "Que cette nuit soit remplie de rêves doux et de repos mérité.",
    "Bonne nuit à toi, repose-toi, tu l'as bien mérité.",
    "La nuit porte conseil, dors bien et vois tout plus clair demain.",
    "Que ton sommeil soit aussi paisible que ton cœur est bon.",
    "Bonne nuit, prends soin de toi et à demain.",
    "Laisse la nuit t'offrir le repos que tu mérites.",
    "Que tes rêves cette nuit soient à l'image de ta belle personnalité.",
    "Dors bien, demain est un nouveau départ.",
    "La nuit tombe, il est temps de se reposer. Bonne nuit.",
    "Que le sommeil t'apporte la paix et l'énergie pour demain.",
    "Que la douceur de la nuit t'accompagne jusqu'au matin.",
    "Ferme les yeux, la journée est finie, place au repos.",
    "Que ton oreiller soit doux et tes rêves encore plus doux.",
    "La nuit est là pour recharger tes batteries, dors bien.",
    "Que demain t'apporte tout ce que tu mérites, bonne nuit.",
    "Un dernier sourire avant de dormir, et voilà, bonne nuit.",
    "Que les soucis du jour restent derrière toi cette nuit.",
    "Bonne nuit, puisses-tu te réveiller aussi reposé(e) que serein(e).",
    "La nuit efface la fatigue, dors bien et prends soin de toi.",
    "Que ton sommeil soit une parenthèse de calme bien méritée.",
    "Bonne nuit, à demain pour de nouvelles aventures.",
    "Laisse le monde tourner sans toi ce soir, repose-toi.",
    "Que cette nuit soit douce comme un murmure et calme comme le silence.",
    "Dors bien, la nuit porte toujours de bons présages.",
    "Que ton sommeil te ressource pour affronter demain avec le sourire.",
    "Bonne nuit, ferme les yeux et laisse-toi bercer par le calme.",
    "Que les rêves les plus doux viennent te rendre visite cette nuit.",
    "La nuit tombe doucement, il est temps de te reposer aussi.",
    "Que ton repos soit à la hauteur de tous tes efforts aujourd'hui.",
    "Bonne nuit, demain sera un jour tout neuf, plein de promesses.",
    "Que le calme de la nuit t'apaise et t'apporte la sérénité.",
    "Dors paisiblement, la nuit est ton alliée.",
    "Bonne nuit, puisses-tu rêver de tout ce qui te rend heureux(se).",
    "Que cette nuit t'offre le repos que ton corps et ton esprit méritent.",
    "Ferme les yeux, respire, et laisse la nuit faire son travail. Bonne nuit.",
    "Bonne nuit, à demain pour de nouveaux sourires.",
    "Que le sommeil t'enveloppe comme une douce couverture.",
    "La nuit est le moment parfait pour tout oublier et se reposer.",
    "Bonne nuit, puisse ton sommeil être aussi léger que tes soucis.",
    "Que les étoiles veillent sur ton sommeil cette nuit.",
    "Dors bien, la nuit porte toujours de nouvelles idées pour demain.",
    "Bonne nuit, que ton repos soit total et ton réveil plein d'énergie.",
    "Que cette nuit soit un vrai moment de pause bien mérité.",
    "Ferme les yeux, il est temps de recharger les batteries. Bonne nuit.",
    "Bonne nuit, puisses-tu dormir du sommeil du juste.",
    "Que le silence de la nuit t'apporte la paix intérieure.",
    "Dors bien, demain t'appartient déjà.",
    "Bonne nuit, à bientôt dans le monde des rêves.",
    "Que cette nuit soit douce et ton réveil encore plus beau.",
    "Ferme les yeux, la nuit prend soin de toi. Bonne nuit.",
    "Bonne nuit, puisse chaque heure de sommeil te rendre plus fort(e).",
    "Que le repos de cette nuit t'apporte la clarté pour demain.",
    "Dors bien, tu as bien mérité cette pause.",
    "Bonne nuit, que ton esprit s'apaise et que ton cœur se repose.",
    "Que cette nuit t'apporte tout le repos dont tu as besoin.",
    "Ferme les yeux, la journée est derrière toi. Bonne nuit.",
    "Bonne nuit, puisse le sommeil t'apporter de belles surprises.",
    "Que le calme de cette nuit soit à la hauteur de tes espoirs pour demain.",
    "Dors bien, demain commence une nouvelle histoire.",
    "Bonne nuit, que tout ce qui est lourd s'allège avec le sommeil.",
    "Que cette nuit soit un vrai cocon de douceur pour toi.",
    "Ferme les yeux, laisse la fatigue s'envoler. Bonne nuit.",
    "Bonne nuit, puisse ton sommeil être aussi beau que toi.",
    "Que le repos t'apporte la force pour un nouveau départ demain.",
    "Dors bien, chaque nuit est une chance de recommencer.",
    "Bonne nuit, à demain pour de nouvelles belles choses.",
    "Que cette nuit t'apporte calme, paix et repos mérité.",
    "Ferme les yeux, la nuit veille sur toi. Bonne nuit.",
    "Bonne nuit, puisse ton sommeil te rendre encore plus radieux(se).",
    "Que le repos de ce soir illumine ta journée de demain.",
    "Dors bien, tu le mérites amplement.",
    "Bonne nuit, que les rêves t'emmènent là où tu es heureux(se).",
    "Que cette nuit efface toute fatigue et n'apporte que du bien-être.",
    "Ferme les yeux, il est temps de te ressourcer. Bonne nuit.",
    "Bonne nuit, puisse chaque instant de sommeil te faire du bien.",
    "Que le calme nocturne t'apporte tout le repos nécessaire.",
    "Dors bien, demain est une nouvelle occasion de briller.",
    "Bonne nuit, que ton sommeil soit profond et réparateur.",
    "Que cette nuit t'apporte la paix avant un jour nouveau.",
    "Ferme les yeux, dors bien, et fais de beaux rêves. Bonne nuit."
];

async function goodnightCommand(sock, chatId, message) {
    try {
        const goodnightMessage = goodnightMessages[Math.floor(Math.random() * goodnightMessages.length)];
        await sock.sendMessage(chatId, { text: goodnightMessage }, { quoted: message });
    } catch (error) {
        console.error('Error in goodnight command:', error);
        await sock.sendMessage(chatId, { text: '❌ Une erreur est survenue. Réessaie plus tard !' }, { quoted: message });
    }
}

module.exports = { goodnightCommand };
