const rosedayMessages = [
    "Une rose pour toi aujourd'hui, comme un symbole de tout ce que tu représentes pour moi.",
    "Comme une rose, tu illumines chaque jour de ta présence.",
    "Je t'offre une rose, simple mais sincère, comme mes sentiments pour toi.",
    "Chaque pétale de cette rose représente une raison de t'apprécier.",
    "Une rose fane, mais mon affection pour toi ne fait que grandir.",
    "Tu es la rose la plus précieuse de mon jardin de souvenirs.",
    "Comme une rose au petit matin, ta présence rend tout plus beau.",
    "Je n'ai pas besoin d'un bouquet entier, une seule rose suffit à te dire ce que je ressens.",
    "Une rose rouge pour dire ce que les mots ont du mal à exprimer.",
    "Ta beauté n'a rien à envier à celle des plus belles roses.",
    "Cette rose est un petit geste pour un sentiment immense.",
    "Comme une rose, tu as su fleurir dans mon cœur.",
    "Je t'envoie une rose, avec tout ce qu'elle représente de sincère et de doux.",
    "Chaque rose a ses épines, mais toi, tu n'as que de belles qualités.",
    "Une rose pour te rappeler à quel point tu comptes pour moi.",
    "Ta présence est comme une rose fraîche, elle embellit chaque instant.",
    "Aujourd'hui, une rose. Tous les jours, une pensée pour toi.",
    "Comme cette rose, mon affection pour toi reste toujours vivante.",
    "Une rose ne dit qu'une petite partie de tout ce que je ressens.",
    "Tu mérites bien plus qu'une rose, mais c'est un début pour te le montrer.",
    "Cette rose porte tout mon respect et toute mon affection.",
    "Comme une rose s'ouvre au soleil, mon cœur s'ouvre à toi.",
    "Une rose pour illuminer ta journée comme tu illumines la mienne.",
    "Ta délicatesse me rappelle celle d'une rose au printemps.",
    "Je t'offre cette rose, simple mais remplie de sincérité.",
    "Comme une rose, tu es unique et précieux(se) à mes yeux.",
    "Cette rose symbolise tout le bien que je te souhaite.",
    "Une rose aujourd'hui pour te dire que je pense à toi.",
    "Ta beauté intérieure surpasse celle de la plus belle des roses.",
    "Que cette rose t'apporte autant de bonheur que tu m'en apportes.",
    "Une rose de plus, un sourire en plus sur ton visage, j'espère.",
    "Comme une rose bien entretenue, notre lien mérite d'être chéri chaque jour.",
    "Cette rose porte en elle tout ce que je n'arrive pas toujours à dire.",
    "Tu rends chaque jour aussi beau qu'un jardin de roses au printemps.",
    "Une simple rose pour un sentiment qui, lui, n'a rien de simple.",
    "Comme les pétales d'une rose, chaque moment avec toi est précieux.",
    "Cette rose est pour toi, pour tout ce que tu représentes dans ma vie.",
    "Ta gentillesse est aussi rare et précieuse qu'une rose en plein hiver.",
    "Une rose pour te rappeler que tu comptes énormément.",
    "Comme une rose, ta présence adoucit tout autour de toi.",
    "Je t'offre cette rose comme un petit clin d'œil à un grand sentiment.",
    "Ta beauté, comme celle d'une rose, ne cesse de m'impressionner.",
    "Une rose pour dire merci d'être exactement qui tu es.",
    "Comme chaque rose est unique, tu l'es aussi à mes yeux.",
    "Cette rose t'est offerte avec toute la sincérité de mon cœur.",
    "Une rose aujourd'hui, une pensée pour toi chaque jour.",
    "Comme une rose s'épanouit lentement, notre complicité grandit chaque jour.",
    "Cette rose représente tout ce que les mots peinent à exprimer.",
    "Ta présence est un vrai bouquet de bonheur dans ma vie.",
    "Une rose pour illuminer ta journée comme tu illumines la mienne.",
    "Comme une rose au lever du jour, tu apportes toujours de la fraîcheur.",
    "Cette rose est mon petit merci pour tout ce que tu es.",
    "Une rose, simple et sincère, comme mon attachement pour toi.",
    "Ta douceur me rappelle celle des plus belles roses du jardin.",
    "Comme une rose, tu sais fleurir même dans les moments difficiles.",
    "Cette rose porte tous mes vœux de bonheur pour toi.",
    "Une rose pour dire, sans grands mots, à quel point tu comptes.",
    "Comme chaque rose a son parfum unique, tu as ta propre magie.",
    "Cette rose est un petit geste pour un sentiment qui, lui, est immense.",
    "Ta bonté est aussi belle qu'un bouquet de roses fraîches.",
    "Une rose pour te dire que je pense à toi, aujourd'hui et toujours.",
    "Comme une rose, notre lien mérite d'être arrosé d'attention chaque jour.",
    "Cette rose t'est offerte avec toute la tendresse que je ressens.",
    "Ta présence rend chaque journée aussi belle qu'un champ de roses.",
    "Une rose pour célébrer tout ce que tu apportes autour de toi.",
    "Comme une rose qui s'ouvre au soleil, ton sourire illumine tout.",
    "Cette rose symbolise l'affection sincère que j'ai pour toi.",
    "Ta délicatesse et ta force réunies, comme une rose et ses épines.",
    "Une rose pour te rappeler que tu mérites d'être choyé(e).",
    "Comme une rose, tu restes belle même dans la simplicité.",
    "Cette rose est pour toi, avec toute la reconnaissance que j'ai.",
    "Ta joie de vivre est un vrai jardin de roses pour ceux qui t'entourent.",
    "Une rose pour dire que tu rends le monde un peu plus beau.",
    "Comme une rose fraîchement cueillie, ta présence est un cadeau.",
    "Cette rose porte en elle tout mon respect et mon affection sincère.",
    "Ta bienveillance est aussi précieuse qu'une rose rare.",
    "Une rose pour t'accompagner aujourd'hui, comme mes pensées.",
    "Comme une rose, tu sais apporter de la couleur à chaque moment.",
    "Cette rose est un symbole simple pour un sentiment sincère et profond.",
    "Ta présence dans ma vie est comme un jardin toujours en fleur.",
    "Une rose pour te dire, encore une fois, à quel point tu comptes.",
    "Comme une rose, ton sourire ne cesse jamais de me toucher.",
    "Cette rose t'est offerte avec toute la douceur que tu m'inspires.",
    "Ta générosité fleurit comme les plus belles roses du printemps.",
    "Une rose pour illuminer ce jour et tous les autres qui suivront.",
    "Comme une rose, tu sais rester belle même face aux tempêtes.",
    "Cette rose porte un message simple : merci d'exister.",
    "Ta présence est le plus beau bouquet que la vie m'ait offert.",
    "Une rose pour toi, avec toute la tendresse de ce moment.",
    "Comme une rose, notre histoire mérite d'être cultivée avec soin.",
    "Cette rose symbolise tout ce que je ressens et n'ose pas toujours dire.",
    "Ta beauté intérieure surpasse celle de n'importe quelle fleur.",
    "Une rose pour te souhaiter autant de bonheur que tu en donnes.",
    "Comme une rose, tu apportes de la lumière partout où tu passes.",
    "Cette rose est le reflet sincère de mon affection pour toi.",
    "Ta présence rend chaque instant aussi précieux qu'une rose rare.",
    "Une rose pour dire, simplement, que tu comptes énormément pour moi.",
    "Comme une rose, tu mérites d'être admiré(e) et chéri(e).",
    "Cette rose t'est offerte avec tout mon cœur, aujourd'hui et toujours.",
    "Une rose pour clore ce jour comme il a commencé : en pensant à toi."
];

async function rosedayCommand(sock, chatId, message) {
    try {
        const rosedayMessage = rosedayMessages[Math.floor(Math.random() * rosedayMessages.length)];
        await sock.sendMessage(chatId, { text: rosedayMessage }, { quoted: message });
    } catch (error) {
        console.error('Error in roseday command:', error);
        await sock.sendMessage(chatId, { text: '❌ Une erreur est survenue. Réessaie plus tard !' }, { quoted: message });
    }
}

module.exports = { rosedayCommand };
